accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

# 회원가입
urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name= 'logout'),
]

articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'

urlpatterns = [
    # create
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name = 'detail'),

    # update
    path('<int:id>/update/', views.update, name='update'),

    # delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # comment_create 
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    
    # comment_delete
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass
    # phone = models.CharField(max_length=100) 

articles/models.py
from django.db import models
from accounts.models import User 
from django.conf import settings
# Create your models here.

# 게시글 
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    # comment_set 

# 댓글 
class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    article = models.ForeignKey(Article, on_delete = models.CASCADE)

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# signup
class CustomUserCreationForm(UserCreationForm):
    class Meta():
        model = User
        #fields = '__all__'
        fields = ('username',) # password도 같이 나옴
        
# login
class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta():
        model = Article
        # fields = '__all__'
        exclude = ('user',)

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST) # 내가 커스텀한 form 불러오기
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'signup.html',context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())

            next_url = request.GET.get('next')

            return redirect(next_url or 'articles:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form':form,
    }
    return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles':articles,
    }
    return render(request, 'index.html',context)

@login_required
def create(request):
     if request.method == 'POST':
         form = ArticleForm(request.POST) # title, content
         if form.is_valid():
             article = form.save(commit=False) # 임시 저장
             article.user = request.user # 로그인한 유저 정보
             article.save()
             return redirect('articles:index')
     else:
         form = ArticleForm()
     
     context = {
         'form':form,
     }
     return render(request, 'create.html', context)

@login_required
def detail(request,id):
    article = Article.objects.get(id=id)
    form = CommentForm(request.POST)
    
    context = {
        'article':article,
        'form':form,
    }
    return render(request, 'detail.html', context)

@login_required
def update(request, id):
    article = Article.objects.get(id=id)

    if request.user != article.user:
        return redirect('articles:index')

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)
    
    else:
        form = ArticleForm(instance=article)

    context = {
        'form':form,
    }
    return render(request, 'update.html', context)

@login_required
def delete(request, id):
    article = Article.objects.get(id=id)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')

@login_required
def comment_create(request, article_id): # 댓글은 get 요청으로 들어오는 경우 없음.
    form = CommentForm(request.POST)
    if form.is_valid():                               
        comment = form.save(commit = False)           

        comment.user_id = request.user.id
        comment.article_id = article_id

        # comment.user = request.user                  
        # article = Article.objects.get(id=article_id) 
        # comment.article = article    
        comment.save()                                   

    return redirect('articles:detail',id=article_id)

@login_required
def comment_delete(request, article_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()
    
    return redirect('articles:detail', id=article_id)  

accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-primary mt-3">
    </form>
{% endblock %}

articles/templates/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-primary mt-3">
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    <h3>{{article.title}}</h3>
    <p>{{article.content}}</p>
    <p>{{article.user}}</p>

    {% if user == article.user %}
        <a href="{% url 'articles:update' article.id %}" class="btn btn-info mt-2">update</a>
        <a href="{% url 'articles:delete' article.id %}" class="btn btn-info mt-2">delete</a>
    {% endif %}

    <hr>
    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" class="btn btn-warning">
    </form>

    <hr>
    {% for comment in article.comment_set.all %}
        <li>{{comment.user.username}} - {{comment.content}}</li>
        {% if user == comment.user %}
            <a href="{% url 'articles:comment_delete' article.id comment.id %}" class="btn btn-danger mt-3">delete</a>
        {% endif %}
    {% endfor %}
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
    <h1>index</h1>

    <hr>
    {% for article in articles %}
        <h3>{{article.title}}</h1>
        <p>{{article.content}}</p>
        <p>{{article.user}}</p>
        <a href="{% url 'articles:detail' article.id %}" class="btn btn-primary">detail</a>
        <hr>
    {% endfor %}
{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method='POST'>
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        {% if user.is_authenticated %}
        <a href="" class="nav-link disabled">{{user}}</a>
        <a href="{% url 'articles:create' %}" class="nav-link">create</a>
        <a href="{% url 'accounts:logout' %}" class="nav-link">logout</a>
        
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="nav-link">signup</a>
        <a href="{% url 'accounts:login' %}" class="nav-link">login</a>
        
        {% endif %}
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>